description: 'University of Trento Cybersecurity research group.'
institution: University of Trento
address: 'Via Sommarive 9, 38123 Povo, Trento, Italy'
social:
  github: 'https://github.com/CybersecurityUnitn/'
  discord: 'https://discord.gg/CybersecurityUnitn'
