name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: golim/hugo-deploy-gh-pages@main
      env:
        TARGET_REPO: CybersecurityUnitn/CybersecurityUnitn.github.io
        TARGET_BRANCH: gh-pages
        HUGO_EXTENDED: true
        HUGO_PUBLISH_DIR: /github/workspace/public
        TOKEN: ${{ secrets.TOKEN }}
        GO_VERSION: 1.17
